FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY . .
COPY ../frontend/build ./frontend_build

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]